import "~/styles/globals.css";
import { Toaster } from "../components/ui/toaster";
import { Inter, Kanit, Montserrat } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import AuthProvider from "./_components/auth-provider";
import Navbar from "./_components/navbar";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// const montserrat = Montserrat({ weight: "400", subsets: ["latin"] });
const kanit = Kanit({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={` ${kanit.className} h-screen bg-violet-50 text-zinc-950`}
      >
        <AuthProvider>
          <Navbar />
          <div className="container mx-auto bg-violet-50">
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
